### ISSUE TITLE
Support for Deduplication

### ISSUE THREAD

**Issue by waltertamboer** [wshafer/psr11-monolog#1]
Support for Deduplication is missing. Any idea how to fix this since we need to load an additional handler. Also, wouldn't it be an idea to add the ContainerInterface to the factories as well?

**Comment by wshafer** [comment]
Hi Walter,

Thanks for bring up this issue.   At the time of writing I deliberately left out the Wrappers/Special handlers, simply because these require a handler themselves and seemed more for special use-cases.  That said, I think I can add these now since this package is a bit more complete then when I started.  Keep an eye out for an update.

As for giving these factories the container, I do that in some.  Since not many of them actually need the container, I do this by looking if the factory implements an interface in a older ZF2 style approach.  So if you're looking to make your own factory (which is absolutely doable) and you want the container in there... as of right now it'll need to implement the ContainerAwareInterface.

Now to answer your original question...  

> Any idea how to fix this since we need to load an additional handler.

For now, you could simply create your own factory and register it.  I know not ideal and defeats the whole reason for using this library, but until I can resolve the recursive dependency and allow for handlers to include other handlers, it's the best I got right now.

**Comment by wshafer** [comment]
@waltertamboer - Ok the Deduplification has been added to the master branch.  There's a couple of others I'd like to get in before pushing a new release.  Until then, you can switch composer to use "dev-master" and you should be good to go.  The docs have also been updated for these new handlers as well.

Thanks again and let me know if you have any more issues.

**Comment by waltertamboer** [comment]
Hi @wshafer 

I can confirm it works. Thanks for your help! We're making a logging module for Zend Framework and your factories save a lot of time. Will let you know when we've published the module :+1:
